{{- if empty .Values.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "s3proxy.fullname" . }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
stringData:
  {{- if not .Values.environmentSecrets.AWS_ACCESS_KEY_ID }}
  AWS_ACCESS_KEY_ID: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- if not .Values.environmentSecrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.environmentSecrets }}
  {{ $key }}: {{ $value  | quote }}
  {{- end }}
{{- end }}
