name: Deploy test version
on:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  package-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./s3proxy
    steps:
    - uses: actions/checkout@v4
    - name: Set up Helm
      uses: azure/setup-helm@v4
    - name: Login to Github Container Registry
      run: |
        echo ${{secrets.OCI_REGISTRY_PASSWORD}} | helm registry login ${{ vars.OCI_REGISTRY_URL }} --username ${{ github.actor }} --password-stdin
    - name: Get chart version
      id: get_chart_version
      run: |
        version=$(yq e '.version' Chart.yaml)
        echo "result=${version}" >> $GITHUB_OUTPUT
    - name: Set calculated chart version
      if: ${{ github.ref != 'refs/heads/main' }}
      run: |
        echo "CURRENT_VERSION=${{ steps.get_chart_version.outputs.result }}-alpha" >> $GITHUB_ENV
    - name: Set calculated chart version
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        echo "CURRENT_VERSION=${{ steps.get_chart_version.outputs.result }}-beta" >> $GITHUB_ENV
    - name: Build and push chart
      run: |
        fileName=$(helm package . --version "$CURRENT_VERSION" | grep -Po "([a-zA-Z0-9-\.]*.tgz)$")
        helm push $fileName "oci://${{ vars.OCI_REGISTRY_URL }}/helm"
